github.com:
    users:
        xdagiz:
            oauth_token: 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
    git_protocol: ssh
    user: xdagiz
    oauth_token: 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
