[general]
import = ["/home/xdagiz/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "alacritty"

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "v"
mods = "Control|Shift"

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/usr/bin/tmux"

[window]
dynamic_padding = true
# opacity = 0.95

[window.padding]
x = 20
y = 14
